### PR TITLE
Some reworked

### PR DESCRIPTION
**Pull request by Piterden**
Seems, something has become hidden. Could you tell me what, please?

### CODE REVIEW

**Comment by agustindidiego** [comment]
The backend goes broken.
These binding shouldn't be set:
```php
BasePanelBuilder::class      => ControlPanelBuilder::class,
        BaseSectionNormalizer::class => SectionNormalizer::class,
```
Doing that, overrides backend functionality.

**Comment by Piterden** [comment]
It could be so.
Sorry, I hurried that time. Just wanted to show a principle to you. There were too much repeated code.

You could bind it by condition, for example.

**Comment by agustindidiego** [comment]
Well, about the repeated code, yes, there is..., I have to clean some extended classes and remove the methods I didn't modify. But binding the classes will not work in this case.

**Comment by Piterden** [comment]
I suppose, I just forget to call `parent::method()` there. It should works, just don't understand, why not?

**Comment by Piterden** [comment]
You are always could call your additional functionality by condition, to avoid calling of it, when you don't want.

**Comment by agustindidiego** [comment]
Because if you bind the classes, they will be used globally instead of the original ones.
For example, if you bind the ControlPanelBuilder class, the admin will going to use mine for the admin instead of the original one..., which is no good, the admin breaks if you do that, because my custom ControlPanelBuilder class is modifying the way it works for the admin. Navigation and Sections are gathered from a config file instead of the Module class, etc...

**Comment by Piterden** [comment]
I understand it.
I propose you to call that parent class next way.
For example if you have to override method:
```php namespace Vendor\SlugModule\Page\Form;

use Illuminate\Http\Request;

class PageFormSections extends \Anomaly\PagesModule\Page\Form\PageFormSections

    protected $request;

    public function __construct(Request $request)
    {
        $this->request = $request;
    }

    public function handle(PageFormBuilder 
       $builder)
        {
            // Here we call the parent class, so nothing should be brocken.
            parent::handle($builder);

            // Here we could implement additional functionality.
            // We would put a condition here.
            // Also, we'd able to check almost anything there. Let it be, for example route from request.
            if ($this->request->is('admin/slugs')))
            {
                // This wouldn't be called on pages/pages route
                $this->doThaShit();
            }
        }
    }
}
```

**Pull request merged**
